### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by deven-gqc** [huggingface/accelerate#1099]
### System Info

```Shell
This bug is regarding the docs.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

The link in `notebook_launcher` (for 0.11) [page](https://huggingface.co/docs/accelerate/v0.11.0/en/launcher) on the line &darr;

An example can be found in [this notebook](https://github.com/huggingface/notebooks/blob/master/examples/accelerate/simple_nlp_example.ipynb) is broken

1. https://github.com/huggingface/notebooks/blob/main/examples/accelerate/simple_nlp_example.ipynb
![image](https://user-images.githubusercontent.com/86305049/220460699-6bd267f1-e4c3-4a2f-a827-62f04fd9d2d1.png)

Also, when I try to see the docs for the launcher for `0.16`, they don't exist.

![image](https://user-images.githubusercontent.com/86305049/220461048-2e690971-9fe3-46dc-a4bd-17a627304d53.png)

### Expected behavior

```Shell
The docs should redirect to the correct page.
```

**Comment by muellerzr** [comment]
The docs were fully redone as part of a latter release, and you should look at https://huggingface.co/docs/accelerate/basic_tutorials/notebook, which also has the right URL. There isn't a way to redirect that currently I believe since it was both a migration on our side (URL) and Github itself. 

Here is the package reference for the launcher: https://huggingface.co/docs/accelerate/package_reference/launchers

**Comment by deven-gqc** [comment]
I think this does the job for me. Thanks Zach.
