### ISSUE TITLE
Any difference with the Facebook fairscale repo?

### ISSUE THREAD

**Issue by zhongpeixiang** [huggingface/accelerate#122]

**Comment by sgugger** [comment]
Hi there! The fairscale repo is yet another API to distributed training. Accelerate is a unified API that regroups various ways to do distributed training. Checkout the [overview in video](https://youtu.be/s7dy8QRgjJ0) for instance.

Closing this since we keep the issues for bugs and feature requests. If you have more questions, please use our [forums](https://discuss.huggingface.co/c/accelerate/18) :-)

**Comment by zhongpeixiang** [comment]
Thanks for the explanation!
