### ISSUE TITLE
Accelerating of two networks

### ISSUE THREAD

**Issue by rose-jinyang** [huggingface/accelerate#161]
Hello
How are you?
Thanks for contributing to this project.
I have two networks in my project; one is a model for training and another is a model for only inference.
While training the first network, the second network is used for only inferencing with the same data.
The training of the first network can be capsulated with the accelerate.
Can the second network using the same input data as the first network data be capsulated by the accelerate?

**Comment by sgugger** [comment]
If you don't compute gradients, you don't necessarily need to pass your inference model to `accelerator.prepare`, you just need to put it on the right device.

**Comment by rose-jinyang** [comment]
Thanks for your reply.
While training the first model, the trained weights of the first network are transferred to the second network from a certain epoch.
Can I use the first network as a general network in a single GPU training?

**Comment by RahulSChand** [comment]
@rose-jinyang 

What do you mean by "use as a general network"? Also `accelerate.save()` is only necessary if you pass your model to the `.prepare` function, otherwise you can directly use `torch.save(...)` . Also since you are on a single GPU instance, you don't even have to call `accelerate.wait_for_everyone()` before calling `torch.save(...)`

**Comment by rose-jinyang** [comment]
The NCCL issue appears when doing inference for the second model.

![image](https://user-images.githubusercontent.com/47862419/133193307-043e26e6-724f-49fc-b6f7-20852943ea6c.png)
