### ISSUE TITLE
Add utility function to save/load all models/optimizers stored in an accelerator

### ISSUE THREAD

**Issue by yuxinyuan** [huggingface/accelerate#171]
Hi all,
I'm not from the nlp regime, but I love the concept of accelerate. However, I would like to propose some new features.

Since every accelerator.prepare call will essentially store a reference of the object in accelerator. It should be easy to implement a save_all()/load_all() utility that saves/loads all the pytorch module and optimizer state dicts to/from a checkpoint. This utility also has the benifit to save and load the state dict of grad scaler, and potentially any other internal states (which are all agnostic to accelerator users)

I guess the singature could look something like `def save_all(self, filename: str, dict_of_additional_usr_data: Dict[str, Any])`

What do the maintainers think of this utility?

**Comment by sgugger** [comment]
Yes, this is on the roadmap and should come in the next few weeks! It will save everything you said plus all the RNG states, so that one can resume training in the exact same conditions. It will also provide an easy way to upload said checkpoint to the Hub so that you can easily resume training on another machine.

I am swamped until the end of next week but hoping to get into adding this the first week of October :-)

**Comment by lvwerra** [comment]
Is this feature still on the roadmap?

**Comment by sgugger** [comment]
Yes, I just need the time to dig into it. I have a few things to wrap up in Transformers but plan to work on Accelerate only afterward for a couple of months.
