### ISSUE TITLE
Accelerate seems to prevent capturing SLURM SIGNAL

### ISSUE THREAD

**Issue by jytime** [huggingface/accelerate#1918]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-5.15.0-1033-aws-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1121.82 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Hi Team,

Thanks for the great work of accelerate. We are using accelerate for multi-GPU/node training in a SLURM system, and the training goes correctly.

Given SLURM jobs may be preempted, we hope the jobs can automatically requeue themseleves when being preempted. Usually this is done by capturing user defined signal such as SIGUSR2. Before switching to accelerate, we used the popular tool [submitit](https://github.com/facebookincubator/submitit/tree/109f7c7f098de6775397e2b84826d59101a29a9f) to implement such a signal capturing mechanism, and an example can be found [here](https://github.com/facebookincubator/submitit/blob/109f7c7f098de6775397e2b84826d59101a29a9f/submitit/core/job_environment.py#L146). 

However, after running jobs as "accelerate launch", it seems the signal cannot be captured anymore. SLURM jobs would be cancelled after preemption, with error log as "srun: error: workers-st-p4de-993: task 0: User defined signal 2." I was wondering, is this because accelerate has its own function to capture SIGUSR signals and intercepts them? It would be great if we could get any instruction on how to let accelerate handle SLURM signals, or other solutions to requeue SLURM jobs.

Our SLURM sbatch command looks like:
```
#!/bin/bash

# Parameters
#SBATCH --array=0-2%3
#SBATCH --cpus-per-gpu=12
#SBATCH --gpus-per-node=8
#SBATCH --job-name=train_S004
#SBATCH --nodes=1
#SBATCH --open-mode=append
#SBATCH --signal=USR2@120
#SBATCH --time=4000
#SBATCH --wckey=submitit

# command
export PYTHONUNBUFFERED='True'
export SUBMITIT_EXECUTOR=slurm
export NCCL_DEBUG=1
export MAIN_PROCESS_PORT=`/data/home/jianyuan/miniconda/envs/jay/bin/python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'`
--unbuffered /fsx-repligen/jianyuan/slurm_jobs/e1847f52797f4c67833a09ad823f4849_accelerate_call.sh
```

The accelerate_call.sh file looks like:

```
#!/bin/bash

echo 'launching with accelerate'
/data/home/jianyuan/miniconda/envs/jay/bin/accelerate launch --num_machines 1 --multi_gpu --debug --mixed_precision no --num_cpu_threads_per_process 4 --num_processes 8 --main_process_port "$MAIN_PROCESS_PORT" -m submitit.core._submit /fsx-repligen/jianyuan/slurm_jobs
```

### Expected behavior

Be able to requeue SLURM jobs after preemption when using accelerate.

**Comment by WarmongeringBeaver** [comment]
I have the same problem: I can confirm that I cannot handle SIGUSR1 signals anymore when launching a script with `accelerate launch`. 🙁 

In ⚡  lightning ⚡ this can be handled by a custom callback, or even with a [default plugin](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.plugins.environments.SLURMEnvironment.html#lightning.pytorch.plugins.environments.SLURMEnvironment)! 
It would be super nice to be able to _at least_ manually hack signal handling with `accelerate`, as this is a scenario of interest for anybody working on a managed cluster...

**Comment by BenjaminBossan** [comment]
I don't know much about this topic, so please correct me if I'm wrong: The issue is not that accelerate somehow intercepts and swallows the signal (say, using a broad `except`). Rather, it is required that we explicitly register the signal and a handle for it. What would be the correct handler for this to work with slurm?

**Comment by muellerzr** [comment]
Agreed. Can you try running via raw `torchrun` and report back what the raised error is and what is being caught? This would help us immensely in setting it up. (I also may peek at lightning to see how that's being done itself but I have a general idea)

**Comment by jytime** [comment]
SLURM typically sends a signal—usually SIGUSR1 or SIGUSR2—to a job several seconds before it gets canceled due to preemption or time-out. There are generally two ways to catch SLURM signals: through a SLURM script or directly within Python. It appears that both Lightning and Submitit do it within python. 

A simplest sample may be as below. When the python signal module receives a predefined signal, it will call "scontrol requeue" to restart the job. If receiving other signals, bypass them. As shown in the [_slurm_sigusr_handler_fn](https://github.com/Lightning-AI/lightning/blob/f1df76ce840119f7baee702ef2df1373e516f12f/src/lightning/pytorch/trainer/connectors/signal_connector.py#L69), Lightning employs a similar but more powerful approach, e.g., supporting features like array slurm jobs.

```
import signal
import socket

def sig_handler(signum, frame):
    print("caught signal", signum)
    print(socket.gethostname(), "USR1 signal caught.")
    # do other stuff to cleanup here
    print("requeuing job " + os.environ["SLURM_JOB_ID"])
    os.system("scontrol requeue " + os.environ["SLURM_JOB_ID"])
    sys.exit(0)


def term_handler(signum, frame):
    print("bypassing sigterm", flush=True)
    pass


def init_slurm_signals():
    signal.signal(signal.SIGUSR1, sig_handler)
    signal.signal(signal.SIGTERM, term_handler)
    print("SLURM signal installed", flush=True)

```

I am not sure about it, while it seems even if I wrote the signal handler by myself, the script launched by accelerate cannot catch a SLURM signal (no logs like "caught signal SIGUSR1"). Rerunning the script without accelerate can work correctly. But it may be also quite possible that I made something wrong somewhere...

**Comment by WarmongeringBeaver** [comment]
> I don't know much about this topic, so please correct me if I'm wrong: The issue is not that accelerate somehow intercepts and swallows the signal (say, using a broad `except`). Rather, it is required that we explicitly register the signal and a handle for it.

Yes, the problem is that `accelerate` does not offer a signal handler of some sort to the user. 

> What would be the correct handler for this to work with slurm?

Something specific to SLURM would be a requeue handler, as seems to be done by [lightning](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.plugins.environments.SLURMEnvironment.html#lightning.pytorch.plugins.environments.SLURMEnvironment). But letting the users handle the signal by themselves would also be okay, it's "just" a convenience wrapper from Lightning.

> I am not sure about it, while it seems even if I wrote the signal handler by myself, the script launched by accelerate cannot catch a SLURM signal

My uneducated guess is that calling `accelerate launch` or `torchrun` starts a process than then itself launches other processes. When SLURM is told to send a SIGUSER (or any other signal), it does so to _that_  `accelerate launch` process only (because it's the only one it knows of) and not to all the processes started by it (and it might not have a simple way to propagate it anyway if the processes do not share the same group id or whatever common kernel identifier).

> Can you try running via raw torchrun and report back what the raised error is and what is being caught?

`torchrun` exhibits the exact same behavior than  `accelerate launch` (the signal is not caught by the user program). It does not offer any user-facing signal handle to my knowledge, nor does it "pass-through" the signals.

**Comment by WarmongeringBeaver** [comment]
> I don't know much about this topic, so please correct me if I'm wrong: The issue is not that accelerate somehow intercepts and swallows the signal (say, using a broad except). Rather, it is required that we explicitly register the signal and a handle for it.

Yes, the problem is that accelerate does not offer a signal handler of some sort to the user.

>    What would be the correct handler for this to work with slurm?

Something specific to SLURM would be a requeue handler, as seems to be done by [lightning](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.plugins.environments.SLURMEnvironment.html#lightning.pytorch.plugins.environments.SLURMEnvironment). But letting the users handle the signal by themselves would also be okay, it's "just" a convenience wrapper from Lightning.

>    I am not sure about it, while it seems even if I wrote the signal handler by myself, the script launched by accelerate cannot catch a SLURM signal

My uneducated guess is that calling accelerate launch or torchrun starts a process than then itself launches other processes. When SLURM is told to send a SIGUSER (or any other signal), it does so to that accelerate launch process only (because it's the only one it knows of) and not to all the processes started by it (and it might not have a simple way to propagate it anyway if the processes do not share the same group id or whatever common kernel identifier).

>    Can you try running via raw torchrun and report back what the raised error is and what is being caught?

torchrun exhibits the exact same behavior than accelerate launch (the signal is not caught by the user program). It does not offer any user-facing signal handle to my knowledge, nor does it "pass-through" the signals.

**Comment by ottonemo** [comment]
> My uneducated guess is that calling accelerate launch or torchrun starts a process than then itself launches other processes. When SLURM is told to send a SIGUSER (or any other signal), it does so to that accelerate launch process only (because it's the only one it knows of) and not to all the processes started by it (and it might not have a simple way to propagate it anyway if the processes do not share the same group id or whatever common kernel identifier).

This is how it works basically, yes - however with default settings for the [`ProctrackType`](https://slurm.schedmd.com/slurm.conf.html) parameter Linux cgroups are used to identify all the processes that belong to the job. The cgroup should be inherited to all subprocesses and, thus, [all processes in the cgroup](https://github.com/SchedMD/slurm/blob/ef670f760a2add1a3a0614e34ab17951cac1f381/src/plugins/proctrack/cgroup/proctrack_cgroup.c#L176) are notified [on preemption](https://github.com/SchedMD/slurm/blob/523319a51f0117e8bd7999c861aa69ef3bda0327/src/interfaces/preempt.c#L451).

I don't see a good reason yet why the submitit handler shouldn't work with `accelerate launch`. Are you using a different proctrac type such as pgid on your SLURM cluster?

**Comment by WarmongeringBeaver** [comment]
I'll test the submitit handler with accelerate, and indeed I don't see why it wouldn't work.
My point –and @jytime's:
> Before switching to accelerate, we used the popular tool submitit to implement such a signal capturing mechanism
 was in the context of using accelerate only.
