### ISSUE TITLE
wait_for_everyone() and other features of Accelerate do not function without shared memory

### ISSUE THREAD

**Issue by bghira** [huggingface/accelerate#1929]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
- Python version: 3.10.11
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 393.40 GB
- GPU type: NVIDIA RTX A6000
- `Accelerate` default config:
        Not found
```

### Information

- [x] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

The above system works, but an equivalent system and environment with the only difference being the kernel version, meant that Accelerate will hang.

I'm not skilled enough in this space to trace down what happens, but really the lack of shared memory in the 5.4 version kernel seems to bring this on.

Using simple multi gpu setup with 2 A6000s and Stable Diffusion 2.1.

### Expected behavior

Accelerate should properly have the `main_process_first()` move on to the child threads.

**Comment by bghira** [comment]
I should add, it freezes as well with `prepare()` when you get rid of all the other state tracking/blocking decorators.

**Comment by bghira** [comment]
yes, unsolved.

**Comment by BenjaminBossan** [comment]
Could you please provide the code leads to the hang?

**Comment by bghira** [comment]
https://github.com/bghira/SimpleTuner/blob/main/train_sdxl.py < this is where it occurs for SDXL

https://github.com/bghira/SimpleTuner/blob/main/train_sd21.py < this is the SD 2.x trainer that caused the problem

it's actually really frustrating. i found some other issues that caused the hang, where the dataset is improperly partitioned between processes - eg. the dataset ends up imbalanced with a few entries short on one process that caused it to move to the next epoch rather than do a backward pass. meanwhile, the other processes that had more (the "correct" amount of data) did not move to the next epoch.

it's hard to reproduce, even with the same codebase and kernel version. some of the 5.4 systems work correctly. but they are just, very slow. other times, it just waits forever - and then NCCL timeout.

**Comment by BenjaminBossan** [comment]
This seems like a really tough issue to debug. Kernel version 5.4 are the GA kernel for Ubuntu 18.04 and 20.04 LTS for another 13 months before EOL, so it would be nice if this worked, but it's also relatively old at this point. Do you have a hardware setup that doesn't allow a newer kernel version to be used?

**Comment by bghira** [comment]
nope - and i would be okay with just a warning being emitted. is that good for you?

**Comment by BenjaminBossan** [comment]
Do you mean a warning that checks for the Linux kernel version?

**Comment by bghira** [comment]
yes

**Comment by BenjaminBossan** [comment]
I see. We could check `platform.uname().release` on startup and give a warning if the version is < 5.5. WDYT?

**Comment by bghira** [comment]
yeah i would have gone for <5.15 but <= 5.5 also works too. that (5.5) was a non-LTS kernel anyway. that said, i don't have access to 5.10 systems to test, either.

**Comment by muellerzr** [comment]
@bghira I do all my tests with `Accelerate` on 5.10 so I know that works :)

**Comment by bghira** [comment]
that covers all bases then. for my perspective, i was just thinking there were _other_ issues in my code that caused this. i would comb through everything, and then ran it in debugger and found that it was all waiting on shared memory. upon further inspection, the Docker runtime complains at startup that the kernel lacks the proper shared memory config, and there's POSSIBLY a way to check `/proc/config.gz` for this info but i don't know what that is. a warning would at least alert the user that their kvers is likely to blame. thank you!

**Comment by miquelmarti** [comment]
I've been going nuts with random NCCL timeouts for a long time and I just saw this issue. I'm on a university cluster with kernel 4.18. I reported this to the cluster administrators but seems very unlikely they will upgrade. Does anyone have any workaround or tips on how to avoid or minimize these issues?

**Comment by Micket** [comment]
(I'm the HPC cluster admin @miquelmarti mentioned).

> but if I read [this](https://en.wikipedia.org/wiki/Linux_kernel_version_history) correctly

What the kernel devs do isn't at all relevant to what distros decide to take on (and what security fixes they backport; they backport a lot).  RHEL8 (4.18 kernel) is EOL in 2029 (even Ubuntu offers their extended support for 5+5 years; [technically 14.04.6 isn't EOL yet](https://wiki.ubuntu.com/Releases) ).

Even leaving aside what hardware vendor supports when building HPC systems (firmware, infiniband, drivers, cluster filesystem support etc), swapping out the OS means redeploying the entire cluster, rebuilding thousands of software packages, probably dropping support for the oldest versions (which might be in active use by many other researchers). This might happen once in the lifetime of a HPC cluster.

I'm curious about  this supposed bug in the kernel though, because
> the lack of shared memory in the 5.4 version kernel

shared memory is absolutely not a new thing in 5.5. It's been around for.. well forever, and is of course used all the time by frameworks like NCCL, MPI/UCX/UCC all the time.

I suggested Miquel start by testing out testing some environment variables like [disabling shm in NCCL](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-shm-disable) just to see if the problem can be isolated.
And depending on what one might glean from that, look into [debug files](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-debug-file) and/or profiling the application with [Scalene](https://github.com/plasma-umass/scalene) and [NVIDIA Nsight](https://developer.nvidia.com/nsight-systems)

Given the use of docker mentioned in the comment, and the fact that HPC schedulers like SLURM also uses cgroups for resource management (no HPC clusters use docker), I'm tempted to think there is a cgroups interplay here.  I'm really curious as to what the exact errors were here:

> @bghira
> upon further inspection, the Docker runtime complains at startup that the kernel lacks the proper shared memory config

**Comment by bghira** [comment]
if you want the Redhat backports to work for you, it'll have to be Redhat (or the vendor) that updates the kernel. those kernels are bad news. they've got too many poorly backported fixes, because redhat can't test every possible combination of software. I would not be surprised if zero pytorch loads run on those test boxes.

did you know Redhat doesn't support NVIDIA? that's something you have to get through nvidia-specific support entitlements. any issues between the Redhat kernel and NVIDIA, you're on your own.

as it is, we had to completely forego the Redhat patched kernel series because all the way up to 5.15 it is **simply broken** for more than one use case. the shared memory hangs are due to incorrectly backported fixes.

getting them to fix it wasn't something my team wanted to spend time on. instead, we switched the fleet to Ubuntu 22.

**Comment by bogan-FMA** [comment]
hey there, does this issue really find the root cause? we are actually getting this error all the time:Detected kernel version 4.15.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher., but sometimes it wait for the train to be started. depending on the data loading. but no hang at all.

**Comment by bghira** [comment]
you really need to upgrade your kernel..
