### ISSUE TITLE
Priority between config file when using deepseed

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/accelerate#2210]
Hi, I am a little bit confused about the configuration of accelerate config and deepspeed config. Say I have a `train.py` with the following init code:
```python
   accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        log_with='wandb',
        mixed_precision='bf16',
    )
```
Also I have a `accelerate_config.yaml` and `deepspeed_config.json`, there are a lot of things i need to care about (e.g. mixed precision, gradient_accumulation_steps, etc.). I just want to know what is the recommended to way to configure all these when I want my `train.py` to accommodate to `single_gpu_training`, `ddp_training` and `deepspeed_training`.

**Comment by muellerzr** [comment]
If you set `gradient_accumulation_steps` to `auto` in the deepspeed config, then it will use the one passed to the `Accelerator`. Otherwise the one used by the plugin has priority. So set it in `Accelerator` and in your `deepspeed_config.json` leave the num accumulation steps as just "auto" :) 

cc @pacman100 if there is anything else I missed

**Comment by pacman100** [comment]
Hello, please refer how to use the simple DeepSpeed plugin integration to get started: https://huggingface.co/docs/accelerate/usage_guides/deepspeed#accelerate-deepspeed-plugin. Specify the gradient accumulation steps there and simply use `accelerator=Accelerator()` without specifying it here as it is already available in the accelerate config.
