### ISSUE TITLE
missing online doc even though the docstring exists

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#2287]
https://huggingface.co/docs/accelerate/main/en/package_reference/accelerator?search=true
doesn't seem to cover all the documented functions/methods.

e.g. searching for `gather_object` gives nada:
![snapshot_526](https://github.com/huggingface/accelerate/assets/10676103/0d7bccf6-48c0-46b4-a2d8-711da2007ad5)

but the docstring is there:
https://github.com/huggingface/accelerate/blob/d1abd59114ada8ba673e1214218cb2878c13b82d/src/accelerate/utils/operations.py#L417-L426

It does find `gather` on the other hand.

**Comment by george-kuanli-peng** [comment]
It seems that searching in accelerate docs does not work. Inputing "gather" does not return results, either.

**Comment by BenjaminBossan** [comment]
Thanks for reporting.

> It does find `gather` on the other hand.

There is an entry for `gather` [here](https://github.com/huggingface/accelerate/blob/403c0714d1dd019a481022afce5df75a9963ecd9/docs/source/package_reference/utilities.md?plain=1#L85) that generates an API reference, but `gather_object` is missing, which is why it doesn't show up. Not sure if there is any logic to which function is included and which isn't, probably this is just an oversight?@muellerzr

> It seems that searching in accelerate docs does not work.

This seems to be a separate issue right now, we're investigating.

**Comment by muellerzr** [comment]
@BenjaminBossan yup there's some missing entries in the utils doc that need to be added. (We don't do everything for the utils, just what is in the `__init__.py` under `utils/` but seems some are missing!

**Comment by BenjaminBossan** [comment]
@george-kuanli-peng The search feature in docs should be working correctly again.

**Comment by stas00** [comment]
unstale, this is still unresolved.

**Comment by muellerzr** [comment]
Thanks Stas, yes indeed. A doc sprint is next on my list as we near 1.0.0 :)

**Comment by stas00** [comment]
unstale, this is still unresolved.

**Comment by muellerzr** [comment]
cc @stevhliu as he's going through all our docs and being fantastic 🤗

**Comment by stas00** [comment]
unstale, this is still unresolved.

**Comment by muellerzr** [comment]
Will get this resolved today 🤗
