### ISSUE TITLE
How to share non-tensor data between processes?

### ISSUE THREAD

**Issue by simonhessner** [huggingface/accelerate#2331]
I am running a training on 2 GPUs on the same machine. I need a way to share some float values and maybe dicts between the two processes. I saw that there is a `gather` method, but this only works for tensors.

Is there any way to do inter-process communication that is not directly related to the training?

EDIT: What I want to do is log the AVERAGE training error of my model after each epoch. The problem is that the process I am logging from only sees the training error that was computed in this process

**Comment by BenjaminBossan** [comment]
> I saw that there is a `gather` method, but this only works for tensors.

You can store floats in a tensor, so that should be fine.

Also take a look at [gather_for_metrics](https://huggingface.co/docs/accelerate/v0.26.1/en/package_reference/accelerator#accelerate.Accelerator.gather_for_metrics).

For a more general distributed key-value store, take a look at [this](https://pytorch.org/docs/stable/distributed.html#distributed-key-value-store).

**Comment by geronimi73** [comment]
> I saw that there is a `gather` method, but this only works for tensors.

use `gather_object` to gather any object

https://github.com/huggingface/accelerate/issues/2188#event-11380179367

**Comment by simonhessner** [comment]
Thanks @geronimi73
That is exactly what I was looking for. I didn't see it because I wasn't aware there is a utils module
