### ISSUE TITLE
activateEnvironment.sh is missing from the repository

### ISSUE THREAD

**Issue by scvance** [huggingface/accelerate#2370]
activateEnvironment.sh is referenced in the slurm example linked here https://github.com/huggingface/accelerate/blob/main/examples/slurm/submit_multinode.sh

I cannot find the file activateEnvironment.sh anywhere.

Any help would be greatly appreciated. Thanks!

**Comment by muellerzr** [comment]
cc @TJ-Solergibert :)

**Comment by TJ-Solergibert** [comment]
In the activateEnvironment.sh you should include the steps to activate the environment to run the experiments. This includes setting up the python interpreter, environment variables, etc. 

The following configuration is what I need to do in my cluster in order to run the experiments. First I load the necessary modules to load anaconda and GPU dependencies. Then I activate the conda environment which I want to use to perform the experiments. Finally I set up some environment variables, mainly to run the experiments offline because we don’t have internet access.

‘’’bash
module purge
module load anaconda3/2020.02 cuda/10.2 cudnn/8.0.5 nccl/2.9.9 arrow/7.0.0 openmpi
source activate /home/nct01/nct01328/pytorch_antoni_local

export HF_HOME=/gpfs/projects/nct01/nct01328/
export HF_LOCAL_HOME=/gpfs/projects/nct01/nct01328/HF_LOCAL
export HF_DATASETS_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export PYTHONPATH=/home/nct01/nct01328/transformers-in-supercomputers:$PYTHONPATH 
export GPUS_PER_NODE=4
‘’’

You should end up having something very similar, good luck!
