### ISSUE TITLE
Is it possible to shard model at loading time (FSDP)

### ISSUE THREAD

**Issue by chenmoneygithub** [huggingface/accelerate#2515]
Hi team,

I am a bit confused about how the FSDP works with Accelerator. Basically if I run the code below from the TRL SFT example in my 4-GPU instance:
```
base_model = AutoModelForCausalLM.from_pretrained(
    script_args.model_name,
    quantization_config=bnb_config,
    device_map={"": Accelerator().local_process_index},
    trust_remote_code=True,
    use_auth_token=True,
)
```
 
I noticed that the model was loaded fully in each GPU (I was using Llama 13B + int4 loading, and each GPU had ~8GB memory usage), and during training, the optimizer/model seems not to be sharded since the memory utilization was super high when I set `per_device_batch_size=1`. I am wondering is there anything I am doing wrong? I couldn't find relative information on the official site. Thank you!

**Comment by fancyerii** [comment]
see [this issue](https://github.com/TimDettmers/bitsandbytes/issues/1092#issuecomment-1969161870). QLora(load_in_4bits) is not compatible with fsdp/deepspeed.
try with --use_bnb=False.

I also recommend use deepspeed instead of fsdp. In my own experence, fsdp is not well implemented. you can read [It’s 2023. Is PyTorch’s FSDP the best choice for training large models?](https://openmmlab.medium.com/its-2023-is-pytorch-s-fsdp-the-best-choice-for-training-large-models-fe8d2848832f)

**Comment by BenjaminBossan** [comment]
We added some examples to the PEFT docs on how to run:

- [QLoRA with FSDP](https://huggingface.co/docs/peft/accelerate/fsdp#use-peft-qlora-and-fsdp-for-finetuning-large-models-on-multiple-gpus)
- [QLoRA with DeepSpeed](https://huggingface.co/docs/peft/accelerate/deepspeed#compatibility-with-bitsandbytes-quantization--lora)

Maybe you can find something there that helps with your issue.
