### ISSUE TITLE
Passing multiple models with DeepSpeed will fail

### ISSUE THREAD

**Issue by Fodark** [huggingface/accelerate#253]
## My accelerate config
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 0
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you want to use DeepSpeed? [yes/NO]: yes
How many processes in total will you use? [1]: 1
Do you wish to use FP16 (mixed precision)? [yes/NO]: NO

## Enviroment Info
Machine Info : V100 X 1
accerlerate version : 0.5.1

## (semi-)reproducible code
```
model1 = torch.nn.Transformer()
model2 = torch.nn.Transformer()
opt = torch.optim.Adam(...)
loader = ...

model1, model2, opt, loader = accelerator.prepare(model1, model2, opt, loader)
```
## Additional Explanation

Using DeepSpeed passing multiple models to prepare will fail, i.e. all the models will become the same as the last passed.
This is due to how `_prepare_deepspeed` handles the arguments, especially:

```
for obj in result:
            if isinstance(obj, torch.nn.Module):
                model = obj
            elif isinstance(obj, (torch.optim.Optimizer, dict)):
                optimizer = obj
```

In this way `model` will take only the last `nn.Module` object passed and therefore the `engine` object created later on will be wrong.

**Comment by sgugger** [comment]
Yes the DeepSpeed integration only handles one model and one optimizer for now. We'll work on support for more in the near future.

**Comment by Fodark** [comment]
Thanks for the answer, is there any workaround for the time being to circumvent this limitation?

**Comment by vanakema** [comment]
Any update on this? I'm trying to train stable diffusion using the Dreambooth technique, and I was hoping to use Deepspeed to enable me to train on my RTX 3090 as I'm running out of memory. I found the issue was that the `StableDiffusionPipeline` is not a `torch.nn.Module` because it's composed of multiple models. I thought a solution might be to call accelerator.prepare() multiple times, once for each of the models that we're training, but I feel like that has the possibility to create multiple Deepspeed instances that wouldn't work in concert with each other. Any advice for folks in my situation?

**Comment by pacman100** [comment]
Hello @vanakema, we looked into support for multiple models with DeepSpeed but it wasn't possible for the following reasons:
1. User only provides a single set of DeepSpeed config plugin/DeepSpeed config files corresponding to a single model. Ideally, the user should have different DeepSpeed configs for multiple models, and this is a niche scenario.
2. DeepSpeed needs to keep track of the model, its optimizer and scheduler and therefore only one global DeepSpeed engine wrapper to control the `backward` and optimizer/scheduler `step`. 

For this scenario, can you please try out the PyTorch FSDP integration. It should follow below format.  
Notes:
1. Same FSDP config would be applicable to both models. 
2. Pass the optimizers to the prepare call in the same order as the corresponding models. This is because when using `accelerator.save_state`, optimizer requires the corresponding model. 

```python
# prepare all models before creating optimizers as FSDP flatten model params which breaks already created optimizer and the fact that it is efficient to prepare the model before creating optimizer
model1 = MyCoolModel1()
model2 = MyCoolModel2()
model1, model2 = accelerator.prepare(model1, model2)

opt1 = torch.optim.AdamW(model1.parameters(), lr1)
opt2 = torch.optim.AdamW(model2.parameters(), lr1)
scheduler1 = get_linear_schedule_with_warmup(opt1)
scheduler2 = get_linear_schedule_with_warmup(opt2)
opt1, opt2, scheduler1, scheduler2 = accelerator.prepare(opt1, opt2, scheduler1, scheduler2)

# remaining training loop and eval loop
...
```

**Comment by uygnef** [comment]
> 2\. Pass the optimizers to the prepare call in the same order as the corresponding models. This is because when using `accelerator.save_state`, optimizer requires the corresponding model.
@pacman100 
Hi there! I have a question regarding the latest version. Does it support multiple models? Currently, I am training only the UNet model, but I want to enable stage 3 for all three models. I have modified the code, but unfortunately, it's not working.
```
    vae, _, _, _ = deepspeed.initialize(model=vae, config_params=vae.configig, model_parameters=None)
    text_encoder, _, _, _ = deepspeed.initialize(model=text_encoder, config_params=ds_config)
    unet, optimizer, training_dataloader, _ = deepspeed.initialize(model=unet, config_params=vae.configig, model_parameters=None)
```
Another issue I am facing is that both the text encoder and UNet models need to be trained. How can I modify the code to address this?

**Comment by jaivardhankapoor** [comment]
Hi, this is probably stale but has anyone found a workaround to combining models for DS optimization in accelerate? Specially for multistage models such as LDM, where we only want to optimize a subset of the parameters.

**Comment by liuxz-cs** [comment]
> FSDP integration

Do do you solve this problem with deepspeed_plugin? Can accelerator with deepspeed_plugin work well with more than 1 model?

**Comment by liuxz-cs** [comment]
> Hi, this is probably stale but has anyone found a workaround to combining models for DS optimization in accelerate? Specially for multistage models such as LDM, where we only want to optimize a subset of the parameters.

Do do you solve this problem with deepspeed_plugin? Can accelerator with deepspeed_plugin work well with more than 1 model?

**Comment by pacman100** [comment]
Hello, DeepSpeed integration in Accelerate currently doesn't support multiple models due to the reasons outlined https://github.com/huggingface/accelerate/issues/253#issuecomment-1253231210. We are looking into it but will take time.

**Comment by ninagroot** [comment]
Hi, 
Is there a solution for this already?
Thanks

**Comment by Hzj199** [comment]
> Hi, Is there a solution for this already? Thanks
When training Stable Diffusion XL, I created a new model based on nn.Module that incorporates the text encoder and UNet as attributes of the new model, and the code runs successfully.

**Comment by Hzj199** [comment]
> Hi, Is there a solution for this already? Thanks

When training Stable Diffusion XL, I created a new model based on nn.Module that incorporates the text encoder and UNet as attributes of the new model, and the code runs successfully.

**Comment by Jake-wei** [comment]
> > Hi, Is there a solution for this already? Thanks
> 
> When training Stable Diffusion XL, I created a new model based on nn.Module that incorporates the text encoder and UNet as attributes of the new model, and the code runs successfully.

niubility! Are u willing to share your code? gratitude！！！

**Comment by luowyang** [comment]
> > Hi, Is there a solution for this already? Thanks
> 
> When training Stable Diffusion XL, I created a new model based on nn.Module that incorporates the text encoder and UNet as attributes of the new model, and the code runs successfully.

While this approach can run without complaints, DeepSpeed's hypothesis about only one model getting trained may somehow interfere with the wrapped but non-training models.
