### ISSUE TITLE
log not work properly with muti-GPU

### ISSUE THREAD

**Issue by Oran-Ac** [huggingface/accelerate#381]
When I try to run `run_mlm_no_trainer.py` with multi-GPU on one node, I can't get any log and the output file in TensorBoard is blank. However when I just run on one GPU by `python run_mlm_no_trainer.py`,it works well.

Here is my code:

```python

accelerator = Accelerator(log_with="all", logging_dir=args.output_dir,kwargs_handlers=[DistributedDataParallelKwargs(find_unused_parameters=True)]) if args.with_tracking else Accelerator()
    if accelerator.is_main_process:
        logging.basicConfig(
            format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
            datefmt="%m/%d/%Y %H:%M:%S",
            level=logging.INFO,
        )
        logger.info(accelerator.state, main_process_only=False)
    
        datasets.utils.logging.set_verbosity_warning()
        transformers.utils.logging.set_verbosity_info()

    if args.seed is not None:
        set_seed(args.seed)

    # 加载训练集 测试集
    with open(args.train_file_path,'rb') as f:
        train_dataset = pickle.load(f)
    with open(args.validation_file_path,'rb') as f:
        eval_dataset = pickle.load(f)
    train_dataset = PretrainDataset(train_dataset)
    eval_dataset = PretrainDataset(eval_dataset)
    if accelerator.is_main_process:
        logger.info('[Load dataset]')

```
When I run by `CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7 accelerate launch run_mlm_no_trainer.py ...`accelerate launch 'I just get some warning without any info
![image](https://user-images.githubusercontent.com/44745604/169633458-bb86c597-4a25-4276-ab56-33b661d84e53.png)

However, if I run by `python run_mlm_no_trainer.py ....`
It works.
![image](https://user-images.githubusercontent.com/44745604/169633500-68804c61-287d-44e1-a35f-ae6e89201c33.png)

**Comment by muellerzr** [comment]
Is this the full code formatted correctly **exactly**?

This is the output of me doing `accelerate launch` with the base script you mentioned:
![image](https://user-images.githubusercontent.com/7831895/169910750-66d7046e-403d-4644-becb-2ac5c86f23e4.png)

I can also confirm that the outputs were there.

You also should be able to just use `accelerate launch` without the specified CUDA devices if configured properly.

Here is my minimal version of what you gave, and it's output: 
```python
import datasets
import logging
import transformers

from accelerate import Accelerator
from accelerate.logging import get_logger
from accelerate.utils import DistributedDataParallelKwargs, set_seed

logger = get_logger(__name__)
accelerator = Accelerator(
    log_with="all", 
    logging_dir="mytestdir", 
    kwarg_handlers=[DistributedDataParallelKwargs(find_unused_parameters=True)]
)
if accelerator.is_main_process:
    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )
    logging.info(accelerator.state, main_process_only=False)
    datasets.utils.logging.set_verbosity_warning()
    transformers.utils.logging.set_verbosity_info()

set_seed(42)
if accelerator.is_main_process:
    logger.info('[Load dataset]')
```
A few things to note with what you have here, you only set the format on the main process, and you also only do `logger.info(accelerator.state...)` on the main process. As a result it will only be printed once. And since you don't set the verbosity on the other processes, you'll see the spam you had there. The fix is to mimic the if/else verbosity levels as shown in the original script: 
https://github.com/huggingface/transformers/blob/main/examples/pytorch/multiple-choice/run_swag_no_trainer.py#L271:L282

![image](https://user-images.githubusercontent.com/7831895/169912203-c236a471-156e-4c35-8402-c2ec842e205a.png)

Let me know if you're still having trouble
