### ISSUE TITLE
Debugging in Pycharm

### ISSUE THREAD

**Issue by HashmatShadab** [huggingface/accelerate#535]
I am a new user of accelerate. How should I configure Pycharm in order to debug a program with accelerate? (E.g. accelerate launch main.py)
![Screenshot from 2022-07-19 20-12-11](https://user-images.githubusercontent.com/41732074/179798744-31055fd2-2bd5-417d-9f8c-c8c143168b2d.png)

**Comment by HashmatShadab** [comment]
Any update?

**Comment by LysandreJik** [comment]
Update your run configuration so that it does not use `Script path`, but `Module name` instead. As a module name, input `accelerate.commands.launch`.

As a parameter, add the parameters that you want (in this case, `main.py`).

Here's what my final window looks like:
![image](https://user-images.githubusercontent.com/30755778/180962299-c91d6b7e-705a-4a24-93e8-c619dad48c37.png)

**Comment by HashmatShadab** [comment]
Thank you!

**Comment by RylanSchaeffer** [comment]
@LysandreJik is there any other solution? Or is there a way to disable `accelerate` with `Trainer()`?

**Comment by RylanSchaeffer** [comment]
@LysandreJik this solution doesn't work for me. PyCharm hangs with `Collecting data...`

**Comment by hlwang1124** [comment]
@RylanSchaeffer I meet the same problem. Is there any solution? Thanks.
