### ISSUE TITLE
Support IterableDataset without `__len__` property

### ISSUE THREAD

**Issue by fcakyon** [huggingface/accelerate#600]
Hello,

Currently `accerelate` requires dataset class to have `__len__` method implemented, however most `IterableDataset` implementations do not include `__len__` property by design ([`LabeledVideoDataset` from `PytorchVideo`, for instance](https://github.com/facebookresearch/pytorchvideo/blob/a77729992bcf1e43bf5fa507c8dc4517b3d7bc4c/pytorchvideo/data/labeled_video_dataset.py#L20)).

When I apply `prepare()` over `LabeledVideoDataset` object, it gives this error when training starts:

```bash
Exception has occurred: TypeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
object of type 'LabeledVideoDataset' has no len()
  File "lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 404, in __len__
    length = self._IterableDataset_len_called = len(self.dataset)  # type: ignore[assignment, arg-type]
  File "lib/python3.9/site-packages/accelerate/data_loader.py", line 478, in __len__
    whole_length = super().__len__()
  File "trainer.py", line 168, in fit
    total=len(self.train_dataloader),
  File "finetune_convnext_lstm.py", line 61, in <module>
    trainer.fit()
  File "lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "lib/python3.9/runpy.py", line 197, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
```

Do you have any plans to support `IterableDataset`s that have no `__len__` method?

**Comment by muellerzr** [comment]
This is actually not an issue with Accelerate, this is an issue with the fact that `total` wants to get the length of the dataloader during fit in your `trainer.py` file. 

Accelerate supports dataloaders that don't have a length 😄 

For further debugging, I'd advice opening a thread on the forums since it seems to not be directly from Accelerate but instead a bug with the code you are using: [Hugging Face forums](discuss.huggingface.co/)
