### ISSUE TITLE
backticks in `accelerate`

### ISSUE THREAD

**Issue by deven-gqc** [huggingface/accelerate#731]
Feature request:

Would it possible to include backticks to the source documentation in the docs? Just the way we have it in popular libraries like `fastai`, `numpy`, `pandas`?

**Comment by muellerzr** [comment]
Hi @deven-gqc! Can you please show an example of where you found this doesn't happen in the docs?

**Comment by deven-gqc** [comment]
@muellerzr I was under the impression that even the CLI would have the option of seeing the source code

![image](https://user-images.githubusercontent.com/86305049/193341525-17aabcd6-72e9-45c5-b8d6-04eff5e1eec1.png)

**Comment by muellerzr** [comment]
@deven-gqc since the CLI is a bit of a different functionality than just raw python functions, these can't have autodoc (our documentation rendering system) capabilities and requires manual documentation writing, (sphinx can't render this either), and as a result won't generate a `source`. This is the same case as the `torchrun` docs out of PyTorch. 

fastai is different because it uses `@call_parse` (a `fastcore` capability) to have it be a regular python function, and thus documented as such. We don't depend on fastcore and utilize the standard `argparse` library instead, which results in this difference.

To see the source for any of the CLI aspects, please explore the `commands` subfolder in Accelerate: https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/launch.py

**Comment by deven-gqc** [comment]
Make sense. Thanks a lot Zach! I'll go ahead and close the issue.
