### ISSUE TITLE
Access Global Variables Inside of training_function()

### ISSUE THREAD

**Issue by JosephGatto** [huggingface/accelerate#92]
I am trying to use Accelerate to do large-scale model inference. In particular, I am using T5 to transform strings into a different format on Google's Colab TPUs. 

This has been working fine, as I can print my outputs and verify they are correct. However, when I try to store the model outputs I seem to be unable to do so. The global variables do not seem to be recognized once I run the notebook launcher and I can't return anything from the function. Any advice on how to do this? 

Here is some pseudocode of what I would like to happen 
```
outputs = []
def training_function():
    global outputs
    model = T5ForConditionalGeneration.from_pretrained('t5-base')
    model, dataloader = accelerator.prepare(
        model, dataloader
    )
    for batch in dataloader:
        attention_mask, input_ids = batch['attention_mask'], batch['input_ids']
        output = model.generate(input_ids=input_ids, attention_mask=attention_mask)
        outputs.append(output)

notebook_launcher(training_function)
print(outputs)
```

Thanks!

**Comment by sgugger** [comment]
I don't think this is possible since the process is then forked, so `outputs` gets copied and updated in each process, but there is no way to receive back what each process got with the launcher.

The easiest way I can think of to get some outputs would be to store them in a file, then you can read that file in the main process. You could use the `gather` method to gather all outputs from each process, then save in the main process (with `if accelerator.is_main_process` in your training function for instance.

**Comment by JosephGatto** [comment]
That makes sense. Thanks for the help!
