### ISSUE TITLE
Accelerate with Deepspeed pdsh launcher, main_process_ip, port are not set correctly ?

### ISSUE THREAD

**Issue by lqtrung1998** [huggingface/accelerate#953]
Hello, I'm referring to these lines of code: https://github.com/huggingface/accelerate/blob/v0.15.0/src/accelerate/commands/launch.py#L683-L710

Correct me if I'm wrong but it seem to me that the `main_process_ip/port` is not passed to te `cmd`, so the default value are used.

When I run with `pdsh` launcher with my `main_process_ip/port` passed to the launcher argument, address already in used error is raised (with some log printing about the default id/port in the cmd). But it run ok with `standard` launcher (as the ip/port are set properly there).

Also, I want to ask if there is any pros/cons of using `pdsh` or `standard` or other launcher?

Thank you

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @lqtrung1998, the above PR should handle the `master_port` which is the cause of `address already in used` errors that you are getting. With `standard` launcher, you will have to run the accelerate launch command on each of the nodes whereas when using `pdsh` you need to run the command only on the main node which has passwordless ssh access to all the other nodes, saving you from extra work of running launcher on each node. Please note that `main_process_ip ` isn't used from accelerate config because it will be automatically picked from the `hostfile` and the node on which you run the launcher will be set as main process ip
